# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

trigger: # trigger only affects CI builds
    branches:
        include:
            - main

variables:
    windowsImage: 'windows-2019'

jobs:
    - job: 'FileLists'
      pool:
          vmImage: $(windowsImage)
      steps:
          - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
            displayName: 'Run CredScan'
            inputs:
                toolMajorVersion: V2
                debugMode: false

          - task: securedevelopmentteam.vss-secure-development-tools.build-task-policheck.PoliCheck@1
            displayName: 'Run PoliCheck'
            inputs:
                targetType: F
                SOMEnabled: true

          - task: securedevelopmentteam.vss-secure-development-tools.build-task-report.SdtReport@1
            displayName: 'Generate CodeAnalysisLogs for TSA'
            inputs:
                CredScan: true
                PoliCheck: true

          - task: securedevelopmentteam.vss-secure-development-tools.build-task-publishsecurityanalysislogs.PublishSecurityAnalysisLogs@2
            displayName: 'Publish CodeAnalysisLogs Artifact for Scans tab UI'
            condition: succeededOrFailed()

          - task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@1
            displayName: 'Break build on CredScan violations'
            inputs:
                CredScan: true

          - script: set
            displayName: List environment variables

          - script: dir /s D:\*.* > D_drive.txt
            displayName: List D drive
            condition: always()

          - script: dir /ad C:\*.* > C_drive.txt
            displayName: List C drive (root only)
            condition: always()

          - task: CopyFiles@2
            displayName: 'Copy File lists'
            condition: always()
            inputs:
                Contents: |
                    $(System.DefaultWorkingDirectory)/D_Drive.txt
                    $(System.DefaultWorkingDirectory)/C_Drive.txt

                TargetFolder: '$(System.DefaultWorkingDirectory)/file_lists'

          - task: PublishBuildArtifacts@1
            displayName: publish file lists
            condition: always()
            inputs:
                pathtoPublish: '$(System.DefaultWorkingDirectory)/file_lists'
                artifactName: 'FileLists'
