# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

trigger: # trigger only affects CI builds
    branches:
        include:
            - main

variables:
    windowsImage: 'windows-2019'

jobs:
    - job: 'FileLists'
      timeoutInMinutes: 300
      pool:
          vmImage: $(windowsImage)
      steps:
          - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
            displayName: 'Run CredScan'
            inputs:
                toolMajorVersion: V2
                debugMode: false

          - task: securedevelopmentteam.vss-secure-development-tools.build-task-policheck.PoliCheck@1
            displayName: 'Run PoliCheck'
            inputs:
                targetType: F
                SOMEnabled: true

          - task: securedevelopmentteam.vss-secure-development-tools.build-task-report.SdtReport@1
            displayName: 'Generate CodeAnalysisLogs for TSA'
            inputs:
                CredScan: true
                PoliCheck: true

          - task: securedevelopmentteam.vss-secure-development-tools.build-task-publishsecurityanalysislogs.PublishSecurityAnalysisLogs@2
            displayName: 'Publish CodeAnalysisLogs Artifact for Scans tab UI'
            condition: succeededOrFailed()

          - task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@1
            displayName: 'Break build on CredScan violations'
            inputs:
                CredScan: true

          - script: set
            displayName: List environment variables

          - task: PowerShell@2
            displayName: List C drive
            inputs:
                targetType: inline
                script: Get-ChildItem -LiteralPath C:\ -Attributes Directory -Recurse -Depth 2

          - task: PowerShell@2
            displayName: List D drive
            inputs:
                targetType: inline
                script: Get-ChildItem -LiteralPath D:\ -Attributes Directory -Recurse -Depth 2

          - task: PowerShell@2
            displayName: List exe files on C drive
            inputs:
                targetType: inline
                script: Get-ChildItem -LiteralPath C:\ -Include *.exe -Recurse
