# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: gh-action-staging-validation

jobs:
  build:
    name: Build & check code styling
    runs-on: ubuntu-latest
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    # reused by all "url" cases
    - script: npx serve "${{ github.workspace }}/dev/website-root" -l 5858 &
      name: 'Start /dev/website-root test server at http://localhost:5858'

    - name: [should succeed] case 1: siteDir, no baseline
      uses: microsoft/accessibility-insights-action@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        site-dir: ${{ github.workspace }}/dev/website-root
        output-dir: ${{ github.workspace }}/_case-1
        
    - name: case 1: upload report
      uses: actions/upload-artifact@v2
      with:
          name: accessibility-reports-case-1
          path: ${{ github.workspace }}/_case-1

    - name: '[should succeed] case 2: url, no baseline'
      uses: microsoft/accessibility-insights-action@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        url: http://localhost:5858
        output-dir: ${{ github.workspace }}/_case-2
        
    - name: case 2: upload report
      uses: actions/upload-artifact@v2
      with:
          name: accessibility-reports-case-2
          path: ${{ github.workspace }}/_case-2
     
          
      
